In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris

iris=load_iris()

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target)

In [11]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9473684210526315

In [12]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9736842105263158

In [13]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9473684210526315

In [14]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [20]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9473684210526315

In [22]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [25]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(iris.data):
    x_train,x_test,y_train,y_test=iris.data[train_index],iris.data[test_index],\
                                  iris.target[train_index],iris.target[test_index]
    print(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    print(get_score(SVC(),x_train,x_test,y_train,y_test))
    print(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [26]:
from sklearn.model_selection import cross_val_score



In [28]:
l_scores=cross_val_score(LogisticRegression(),iris.data,iris.target)
l_scores

C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [29]:
np.average(l_scores)

0.9733333333333334

In [30]:
s_scores=cross_val_score(SVC(),iris.data,iris.target)
s_scores


array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [31]:
np.average(s_scores)

0.9666666666666666

In [32]:
r_scores=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
r_scores


array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [34]:
np.average(r_scores)

0.96